#服务器设置
service:
  port: '5214'
mqtt:
  host: ''
  port: ''
  loginName: ''
  password: ''
redis:
  host: ''
  port: ''
  loginName: ''
  password: ''
emqx:
  host: ''
  port: ''
  loginName: ''
  password: ''
  clientId: ''