definitions:
  control.UserLoginService:
    properties:
      password:
        maxLength: 40
        minLength: 8
        type: string
      user_name:
        maxLength: 30
        minLength: 5
        type: string
    required:
    - password
    - user_name
    type: object
  control.UserRegisterService:
    properties:
      password:
        maxLength: 40
        minLength: 8
        type: string
      time:
        maxLength: 40
        minLength: 8
        type: string
      user_name:
        maxLength: 30
        minLength: 5
        type: string
    required:
    - password
    - time
    - user_name
    type: object
info:
  contact: {}
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录权健
      parameters:
      - description: 用户名, 密码, 验证码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/control.UserLoginService'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/control.UserRegisterService'
      summary: 用户登录
      tags:
      - User
swagger: "2.0"
